version: '3'
services:
  web:
    image: node:latest
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app/static
      - ./bs-config.json:/app/bs-config.json
    command: sh -c "npm install -g lite-server && lite-server --config bs-config.json --no-open"

